### ISSUE TITLE
[Bug] Can't import settings with popup on Firefox

### ISSUE THREAD

**Issue by VampireChicken12** [VampireChicken12/youtube-enhancer#176]
When opening the settings popup by clicking the extension icon then clicking "Import Settings" the file picker appears then the settings popup disappears causing this bug

**Comment by rado84-github** [comment]
I don't think that this is a bug, it's a perfectly normal behaviour for all extensions. When the file chooser appears, you just navigate to the settings JSON file and select it. Despite that the pop-up is gone, the browser still remembers what you were gonna do, so it will do it, once you select the JSON file. I know, because I tried that and importing settings worked just fine, even without the pop-up being present.
